//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_Inserting(global::LightSwitchApplication.Icon entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_Inserted(global::LightSwitchApplication.Icon entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_Updating(global::LightSwitchApplication.Icon entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_Updated(global::LightSwitchApplication.Icon entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_Deleting(global::LightSwitchApplication.Icon entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_Deleted(global::LightSwitchApplication.Icon entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_Validate(global::LightSwitchApplication.Icon entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Icons_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Icon, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Inserting(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Inserted(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Updating(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Updated(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Deleting(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Deleted(global::LightSwitchApplication.Menu entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Validate(global::LightSwitchApplication.Menu entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Menus_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Menu, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Inserting(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Inserted(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Updating(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Updated(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Deleting(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Deleted(global::LightSwitchApplication.MenuTile entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Validate(global::LightSwitchApplication.MenuTile entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MenuTiles_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MenuTile, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TilesForMenu_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void TilesForMenu_Executing(string menuName);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TilesForMenu_PreprocessQuery(string menuName, ref global::System.Linq.IQueryable<global::LightSwitchApplication.MenuTile> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void TilesForMenu_Executed(string menuName, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MenuTile> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void TilesForMenu_ExecuteFailed(string menuName, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Icon>
                __IconsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Icon>(
                    "Icons",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Icons_Filter);
            private static bool __Icons_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Icons_CanInsert(ref result);
                return result;
            }
            private static bool __Icons_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Icons_CanUpdate(ref result);
                return result;
            }
            private static bool __Icons_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Icons_CanDelete(ref result);
                return result;
            }
            private static bool __Icons_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Icons_CanRead(ref result);
                return result;
            }
            private static void __Icons_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Icon e)
            {
                d.Icons_Inserting(e);
            }
            private static void __Icons_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Icon e)
            {
                d.Icons_Inserted(e);
            }
            private static void __Icons_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Icon e)
            {
                d.Icons_Updating(e);
            }
            private static void __Icons_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Icon e)
            {
                d.Icons_Updated(e);
            }
            private static void __Icons_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Icon e)
            {
                d.Icons_Deleting(e);
            }
            private static void __Icons_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Icon e)
            {
                d.Icons_Deleted(e);
            }
            private static void __Icons_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Icon e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Icons_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Icon, bool>> __Icons_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Icon, bool>> filter = null;
                d.Icons_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Menu>
                __MenusEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Menu>(
                    "Menus",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Menus_Filter);
            private static bool __Menus_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Menus_CanInsert(ref result);
                return result;
            }
            private static bool __Menus_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Menus_CanUpdate(ref result);
                return result;
            }
            private static bool __Menus_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Menus_CanDelete(ref result);
                return result;
            }
            private static bool __Menus_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Menus_CanRead(ref result);
                return result;
            }
            private static void __Menus_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Inserting(e);
            }
            private static void __Menus_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Inserted(e);
            }
            private static void __Menus_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Updating(e);
            }
            private static void __Menus_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Updated(e);
            }
            private static void __Menus_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Deleting(e);
            }
            private static void __Menus_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e)
            {
                d.Menus_Deleted(e);
            }
            private static void __Menus_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Menu e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Menus_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Menu, bool>> __Menus_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Menu, bool>> filter = null;
                d.Menus_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MenuTile>
                __MenuTilesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MenuTile>(
                    "MenuTiles",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MenuTiles_Filter);
            private static bool __MenuTiles_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MenuTiles_CanInsert(ref result);
                return result;
            }
            private static bool __MenuTiles_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MenuTiles_CanUpdate(ref result);
                return result;
            }
            private static bool __MenuTiles_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MenuTiles_CanDelete(ref result);
                return result;
            }
            private static bool __MenuTiles_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MenuTiles_CanRead(ref result);
                return result;
            }
            private static void __MenuTiles_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Inserting(e);
            }
            private static void __MenuTiles_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Inserted(e);
            }
            private static void __MenuTiles_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Updating(e);
            }
            private static void __MenuTiles_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Updated(e);
            }
            private static void __MenuTiles_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Deleting(e);
            }
            private static void __MenuTiles_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e)
            {
                d.MenuTiles_Deleted(e);
            }
            private static void __MenuTiles_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MenuTile e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.MenuTiles_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MenuTile, bool>> __MenuTiles_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MenuTile, bool>> filter = null;
                d.MenuTiles_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MenuTile>
                __TilesForMenuEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MenuTile>(
                    "TilesForMenu",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TilesForMenu_PreprocessQuery);
            private static bool __TilesForMenu_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.TilesForMenu_CanExecute(ref r);
                return r;
            }
            private static void __TilesForMenu_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.TilesForMenu_Executing((string)args[0]);
            }
            private static void __TilesForMenu_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.TilesForMenu_Executed((string)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MenuTile>)args[1]);
            }
            private static void __TilesForMenu_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.TilesForMenu_ExecuteFailed((string)args[0], ex);
            }
            private static global::System.Linq.IQueryable __TilesForMenu_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.MenuTile> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.MenuTile>)args[1];
                d.TilesForMenu_PreprocessQuery((string)args[0], ref query);
                return query;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the LsSecurityData datasource.
    /// </summary>
    public sealed partial class LsSecurityDataService
        : global::LightSwitchApplication.LsSecurityData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LsSecurityDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_Inserting(global::LightSwitchApplication.Permission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_Inserted(global::LightSwitchApplication.Permission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_Updating(global::LightSwitchApplication.Permission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_Updated(global::LightSwitchApplication.Permission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_Deleting(global::LightSwitchApplication.Permission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_Deleted(global::LightSwitchApplication.Permission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permissions_Validate(global::LightSwitchApplication.Permission entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_Inserting(global::LightSwitchApplication.RoleAssignment entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_Inserted(global::LightSwitchApplication.RoleAssignment entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_Updating(global::LightSwitchApplication.RoleAssignment entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_Updated(global::LightSwitchApplication.RoleAssignment entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_Deleting(global::LightSwitchApplication.RoleAssignment entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_Deleted(global::LightSwitchApplication.RoleAssignment entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleAssignments_Validate(global::LightSwitchApplication.RoleAssignment entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_Inserting(global::LightSwitchApplication.RolePermission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_Inserted(global::LightSwitchApplication.RolePermission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_Updating(global::LightSwitchApplication.RolePermission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_Updated(global::LightSwitchApplication.RolePermission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_Deleting(global::LightSwitchApplication.RolePermission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_Deleted(global::LightSwitchApplication.RolePermission entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermissions1_Validate(global::LightSwitchApplication.RolePermission entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_Inserting(global::LightSwitchApplication.Role entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_Inserted(global::LightSwitchApplication.Role entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_Updating(global::LightSwitchApplication.Role entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_Updated(global::LightSwitchApplication.Role entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_Deleting(global::LightSwitchApplication.Role entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_Deleted(global::LightSwitchApplication.Role entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Roles_Validate(global::LightSwitchApplication.Role entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_Inserting(global::LightSwitchApplication.UserRegistration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_Inserted(global::LightSwitchApplication.UserRegistration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_Updating(global::LightSwitchApplication.UserRegistration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_Updated(global::LightSwitchApplication.UserRegistration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_Deleting(global::LightSwitchApplication.UserRegistration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_Deleted(global::LightSwitchApplication.UserRegistration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistrations_Validate(global::LightSwitchApplication.UserRegistration entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NonSecurityAdministrators_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void NonSecurityAdministrators_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NonSecurityAdministrators_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.UserRegistration> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void NonSecurityAdministrators_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.UserRegistration> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void NonSecurityAdministrators_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentUser_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void CurrentUser_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentUser_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.UserRegistration> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void CurrentUser_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.UserRegistration> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void CurrentUser_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.Permission>
                __PermissionsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.Permission>(
                    "Permissions",
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_CanInsert,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_CanUpdate,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_CanDelete,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_CanRead,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_Inserting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_Inserted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_Updating,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_Updated,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_Deleting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_Deleted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Permissions_Validate,
                    null);
            private static bool __Permissions_CanInsert(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.Permissions_CanInsert(ref result);
                return result;
            }
            private static bool __Permissions_CanUpdate(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.Permissions_CanUpdate(ref result);
                return result;
            }
            private static bool __Permissions_CanDelete(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.Permissions_CanDelete(ref result);
                return result;
            }
            private static bool __Permissions_CanRead(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.Permissions_CanRead(ref result);
                return result;
            }
            private static void __Permissions_Inserting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Permission e)
            {
                d.Permissions_Inserting(e);
            }
            private static void __Permissions_Inserted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Permission e)
            {
                d.Permissions_Inserted(e);
            }
            private static void __Permissions_Updating(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Permission e)
            {
                d.Permissions_Updating(e);
            }
            private static void __Permissions_Updated(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Permission e)
            {
                d.Permissions_Updated(e);
            }
            private static void __Permissions_Deleting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Permission e)
            {
                d.Permissions_Deleting(e);
            }
            private static void __Permissions_Deleted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Permission e)
            {
                d.Permissions_Deleted(e);
            }
            private static void __Permissions_Validate(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Permission e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Permissions_Validate(e, r);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.RoleAssignment>
                __RoleAssignmentsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.RoleAssignment>(
                    "RoleAssignments",
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_CanInsert,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_CanUpdate,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_CanDelete,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_CanRead,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_Inserting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_Inserted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_Updating,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_Updated,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_Deleting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_Deleted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RoleAssignments_Validate,
                    null);
            private static bool __RoleAssignments_CanInsert(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.RoleAssignments_CanInsert(ref result);
                return result;
            }
            private static bool __RoleAssignments_CanUpdate(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.RoleAssignments_CanUpdate(ref result);
                return result;
            }
            private static bool __RoleAssignments_CanDelete(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.RoleAssignments_CanDelete(ref result);
                return result;
            }
            private static bool __RoleAssignments_CanRead(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.RoleAssignments_CanRead(ref result);
                return result;
            }
            private static void __RoleAssignments_Inserting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RoleAssignment e)
            {
                d.RoleAssignments_Inserting(e);
            }
            private static void __RoleAssignments_Inserted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RoleAssignment e)
            {
                d.RoleAssignments_Inserted(e);
            }
            private static void __RoleAssignments_Updating(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RoleAssignment e)
            {
                d.RoleAssignments_Updating(e);
            }
            private static void __RoleAssignments_Updated(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RoleAssignment e)
            {
                d.RoleAssignments_Updated(e);
            }
            private static void __RoleAssignments_Deleting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RoleAssignment e)
            {
                d.RoleAssignments_Deleting(e);
            }
            private static void __RoleAssignments_Deleted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RoleAssignment e)
            {
                d.RoleAssignments_Deleted(e);
            }
            private static void __RoleAssignments_Validate(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RoleAssignment e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.RoleAssignments_Validate(e, r);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.RolePermission>
                __RolePermissions1Entry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.RolePermission>(
                    "RolePermissions1",
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_CanInsert,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_CanUpdate,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_CanDelete,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_CanRead,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_Inserting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_Inserted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_Updating,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_Updated,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_Deleting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_Deleted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__RolePermissions1_Validate,
                    null);
            private static bool __RolePermissions1_CanInsert(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.RolePermissions1_CanInsert(ref result);
                return result;
            }
            private static bool __RolePermissions1_CanUpdate(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.RolePermissions1_CanUpdate(ref result);
                return result;
            }
            private static bool __RolePermissions1_CanDelete(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.RolePermissions1_CanDelete(ref result);
                return result;
            }
            private static bool __RolePermissions1_CanRead(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.RolePermissions1_CanRead(ref result);
                return result;
            }
            private static void __RolePermissions1_Inserting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RolePermission e)
            {
                d.RolePermissions1_Inserting(e);
            }
            private static void __RolePermissions1_Inserted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RolePermission e)
            {
                d.RolePermissions1_Inserted(e);
            }
            private static void __RolePermissions1_Updating(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RolePermission e)
            {
                d.RolePermissions1_Updating(e);
            }
            private static void __RolePermissions1_Updated(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RolePermission e)
            {
                d.RolePermissions1_Updated(e);
            }
            private static void __RolePermissions1_Deleting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RolePermission e)
            {
                d.RolePermissions1_Deleting(e);
            }
            private static void __RolePermissions1_Deleted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RolePermission e)
            {
                d.RolePermissions1_Deleted(e);
            }
            private static void __RolePermissions1_Validate(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.RolePermission e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.RolePermissions1_Validate(e, r);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.Role>
                __RolesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.Role>(
                    "Roles",
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_CanInsert,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_CanUpdate,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_CanDelete,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_CanRead,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_Inserting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_Inserted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_Updating,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_Updated,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_Deleting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_Deleted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Roles_Validate,
                    null);
            private static bool __Roles_CanInsert(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.Roles_CanInsert(ref result);
                return result;
            }
            private static bool __Roles_CanUpdate(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.Roles_CanUpdate(ref result);
                return result;
            }
            private static bool __Roles_CanDelete(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.Roles_CanDelete(ref result);
                return result;
            }
            private static bool __Roles_CanRead(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.Roles_CanRead(ref result);
                return result;
            }
            private static void __Roles_Inserting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Role e)
            {
                d.Roles_Inserting(e);
            }
            private static void __Roles_Inserted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Role e)
            {
                d.Roles_Inserted(e);
            }
            private static void __Roles_Updating(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Role e)
            {
                d.Roles_Updating(e);
            }
            private static void __Roles_Updated(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Role e)
            {
                d.Roles_Updated(e);
            }
            private static void __Roles_Deleting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Role e)
            {
                d.Roles_Deleting(e);
            }
            private static void __Roles_Deleted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Role e)
            {
                d.Roles_Deleted(e);
            }
            private static void __Roles_Validate(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.Role e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Roles_Validate(e, r);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.UserRegistration>
                __UserRegistrationsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.UserRegistration>(
                    "UserRegistrations",
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_CanInsert,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_CanUpdate,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_CanDelete,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_CanRead,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_Inserting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_Inserted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_Updating,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_Updated,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_Deleting,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_Deleted,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__UserRegistrations_Validate,
                    null);
            private static bool __UserRegistrations_CanInsert(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.UserRegistrations_CanInsert(ref result);
                return result;
            }
            private static bool __UserRegistrations_CanUpdate(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.UserRegistrations_CanUpdate(ref result);
                return result;
            }
            private static bool __UserRegistrations_CanDelete(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.UserRegistrations_CanDelete(ref result);
                return result;
            }
            private static bool __UserRegistrations_CanRead(global::LightSwitchApplication.LsSecurityDataService d)
            {
                bool result = true;
                d.UserRegistrations_CanRead(ref result);
                return result;
            }
            private static void __UserRegistrations_Inserting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.UserRegistration e)
            {
                d.UserRegistrations_Inserting(e);
            }
            private static void __UserRegistrations_Inserted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.UserRegistration e)
            {
                d.UserRegistrations_Inserted(e);
            }
            private static void __UserRegistrations_Updating(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.UserRegistration e)
            {
                d.UserRegistrations_Updating(e);
            }
            private static void __UserRegistrations_Updated(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.UserRegistration e)
            {
                d.UserRegistrations_Updated(e);
            }
            private static void __UserRegistrations_Deleting(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.UserRegistration e)
            {
                d.UserRegistrations_Deleting(e);
            }
            private static void __UserRegistrations_Deleted(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.UserRegistration e)
            {
                d.UserRegistrations_Deleted(e);
            }
            private static void __UserRegistrations_Validate(global::LightSwitchApplication.LsSecurityDataService d, global::LightSwitchApplication.UserRegistration e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.UserRegistrations_Validate(e, r);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.LsSecurityDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.LsSecurityDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.LsSecurityDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.LsSecurityDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.LsSecurityDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.LsSecurityDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.UserRegistration>
                __NonSecurityAdministratorsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.UserRegistration>(
                    "NonSecurityAdministrators",
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__NonSecurityAdministrators_CanExecute,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__NonSecurityAdministrators_Executing,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__NonSecurityAdministrators_Executed,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__NonSecurityAdministrators_Failed,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__NonSecurityAdministrators_PreprocessQuery);
            private static bool __NonSecurityAdministrators_CanExecute(global::LightSwitchApplication.LsSecurityDataService d, bool r)
            {
                d.NonSecurityAdministrators_CanExecute(ref r);
                return r;
            }
            private static void __NonSecurityAdministrators_Executing(global::LightSwitchApplication.LsSecurityDataService d, object[] args)
            {
                d.NonSecurityAdministrators_Executing();
            }
            private static void __NonSecurityAdministrators_Executed(global::LightSwitchApplication.LsSecurityDataService d, object[] args)
            {
                d.NonSecurityAdministrators_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.UserRegistration>)args[0]);
            }
            private static void __NonSecurityAdministrators_Failed(global::LightSwitchApplication.LsSecurityDataService d, object[] args, global::System.Exception ex)
            {
                d.NonSecurityAdministrators_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __NonSecurityAdministrators_PreprocessQuery(global::LightSwitchApplication.LsSecurityDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.UserRegistration> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.UserRegistration>)args[0];
                d.NonSecurityAdministrators_PreprocessQuery(ref query);
                return query;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.UserRegistration>
                __CurrentUserEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.LsSecurityDataService, global::LightSwitchApplication.UserRegistration>(
                    "CurrentUser",
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__CurrentUser_CanExecute,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__CurrentUser_Executing,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__CurrentUser_Executed,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__CurrentUser_Failed,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__CurrentUser_PreprocessQuery);
            private static bool __CurrentUser_CanExecute(global::LightSwitchApplication.LsSecurityDataService d, bool r)
            {
                d.CurrentUser_CanExecute(ref r);
                return r;
            }
            private static void __CurrentUser_Executing(global::LightSwitchApplication.LsSecurityDataService d, object[] args)
            {
                d.CurrentUser_Executing();
            }
            private static void __CurrentUser_Executed(global::LightSwitchApplication.LsSecurityDataService d, object[] args)
            {
                d.CurrentUser_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.UserRegistration>)args[0]);
            }
            private static void __CurrentUser_Failed(global::LightSwitchApplication.LsSecurityDataService d, object[] args, global::System.Exception ex)
            {
                d.CurrentUser_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __CurrentUser_PreprocessQuery(global::LightSwitchApplication.LsSecurityDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.UserRegistration> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.UserRegistration>)args[0];
                d.CurrentUser_PreprocessQuery(ref query);
                return query;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.LsSecurityDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.LsSecurityDataService>(
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.LsSecurityDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.LsSecurityDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.LsSecurityDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.LsSecurityDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    #endregion
}
