

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class RolePermission : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the RolePermission entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RolePermission()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RolePermission(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.RolePermission> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.RolePermission.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermission_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolePermission_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RoleName
        {
            get
            {
                return global::LightSwitchApplication.RolePermission.DetailsClass.GetValue(this, global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.RoleName);
            }
            set
            {
                global::LightSwitchApplication.RolePermission.DetailsClass.SetValue(this, global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.RoleName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RoleName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PermissionId
        {
            get
            {
                return global::LightSwitchApplication.RolePermission.DetailsClass.GetValue(this, global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.PermissionId);
            }
            set
            {
                global::LightSwitchApplication.RolePermission.DetailsClass.SetValue(this, global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.PermissionId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PermissionId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PermissionId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PermissionId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Role Role
        {
            get
            {
                return global::LightSwitchApplication.RolePermission.DetailsClass.GetValue(this, global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Role);
            }
            set
            {
                global::LightSwitchApplication.RolePermission.DetailsClass.SetValue(this, global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Role, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Role_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Role_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Role_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Permission Permission
        {
            get
            {
                return global::LightSwitchApplication.RolePermission.DetailsClass.GetValue(this, global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Permission);
            }
            set
            {
                global::LightSwitchApplication.RolePermission.DetailsClass.SetValue(this, global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Permission, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permission_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permission_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permission_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.RolePermission,
                global::LightSwitchApplication.RolePermission.DetailsClass,
                global::LightSwitchApplication.RolePermission.DetailsClass.IImplementation,
                global::LightSwitchApplication.RolePermission.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.RoleName;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass>.Entry
                __RolePermissionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass>.Entry(
                    global::LightSwitchApplication.RolePermission.DetailsClass.__RolePermission_CreateNew,
                    global::LightSwitchApplication.RolePermission.DetailsClass.__RolePermission_Created,
                    global::LightSwitchApplication.RolePermission.DetailsClass.__RolePermission_AllowSaveWithErrors);
            private static global::LightSwitchApplication.RolePermission __RolePermission_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.RolePermission> es)
            {
                return new global::LightSwitchApplication.RolePermission(es);
            }
            private static void __RolePermission_Created(global::LightSwitchApplication.RolePermission e)
            {
                e.RolePermission_Created();
            }
            private static bool __RolePermission_AllowSaveWithErrors(global::LightSwitchApplication.RolePermission e)
            {
                bool result = false;
                e.RolePermission_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.RolePermission.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string> RoleName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.RoleName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string> PermissionId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.PermissionId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Role> Role
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Role) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Role>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Permission> Permission
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Permission) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Permission>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string RoleName { get; set; }
                new string PermissionId { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Role { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Permission { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>.Entry
                    RoleName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>.Entry(
                        "RoleName",
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._RoleName_Stub,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._RoleName_ComputeIsReadOnly,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._RoleName_Validate,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._RoleName_GetImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._RoleName_SetImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._RoleName_OnValueChanged);
                private static void _RoleName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RolePermission.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>.Data> c, global::LightSwitchApplication.RolePermission.DetailsClass d, object sf)
                {
                    c(d, ref d._RoleName, sf);
                }
                private static bool _RoleName_ComputeIsReadOnly(global::LightSwitchApplication.RolePermission e)
                {
                    bool result = false;
                    e.RoleName_IsReadOnly(ref result);
                    return result;
                }
                private static void _RoleName_Validate(global::LightSwitchApplication.RolePermission e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RoleName_Validate(r);
                }
                private static string _RoleName_GetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d)
                {
                    return d.ImplementationEntity.RoleName;
                }
                private static void _RoleName_SetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RoleName = v;
                }
                private static void _RoleName_OnValueChanged(global::LightSwitchApplication.RolePermission e)
                {
                    e.RoleName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>.Entry
                    PermissionId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>.Entry(
                        "PermissionId",
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._PermissionId_Stub,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._PermissionId_ComputeIsReadOnly,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._PermissionId_Validate,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._PermissionId_GetImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._PermissionId_SetImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._PermissionId_OnValueChanged);
                private static void _PermissionId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RolePermission.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>.Data> c, global::LightSwitchApplication.RolePermission.DetailsClass d, object sf)
                {
                    c(d, ref d._PermissionId, sf);
                }
                private static bool _PermissionId_ComputeIsReadOnly(global::LightSwitchApplication.RolePermission e)
                {
                    bool result = false;
                    e.PermissionId_IsReadOnly(ref result);
                    return result;
                }
                private static void _PermissionId_Validate(global::LightSwitchApplication.RolePermission e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PermissionId_Validate(r);
                }
                private static string _PermissionId_GetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d)
                {
                    return d.ImplementationEntity.PermissionId;
                }
                private static void _PermissionId_SetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PermissionId = v;
                }
                private static void _PermissionId_OnValueChanged(global::LightSwitchApplication.RolePermission e)
                {
                    e.PermissionId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Role>.Entry
                    Role = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Role>.Entry(
                        "Role",
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Role_Stub,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Role_ComputeIsReadOnly,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Role_Validate,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Role_GetCoreImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Role_GetImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Role_SetImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Role_Refresh,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Role_OnValueChanged);
                private static void _Role_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RolePermission.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Role>.Data> c, global::LightSwitchApplication.RolePermission.DetailsClass d, object sf)
                {
                    c(d, ref d._Role, sf);
                }
                private static bool _Role_ComputeIsReadOnly(global::LightSwitchApplication.RolePermission e)
                {
                    bool result = false;
                    e.Role_IsReadOnly(ref result);
                    return result;
                }
                private static void _Role_Validate(global::LightSwitchApplication.RolePermission e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Role_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Role_GetCoreImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d)
                {
                    return d.ImplementationEntity.Role;
                }
                private static global::LightSwitchApplication.Role _Role_GetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Role, global::LightSwitchApplication.Role.DetailsClass>(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Role, ref d._Role);
                }
                private static void _Role_SetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d, global::LightSwitchApplication.Role v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Role, ref d._Role, (i, ev) => i.Role = ev, v);
                }
                private static void _Role_Refresh(global::LightSwitchApplication.RolePermission.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Role, ref d._Role);
                }
                private static void _Role_OnValueChanged(global::LightSwitchApplication.RolePermission e)
                {
                    e.Role_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Permission>.Entry
                    Permission = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Permission>.Entry(
                        "Permission",
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Permission_Stub,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Permission_ComputeIsReadOnly,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Permission_Validate,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Permission_GetCoreImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Permission_GetImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Permission_SetImplementationValue,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Permission_Refresh,
                        global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties._Permission_OnValueChanged);
                private static void _Permission_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RolePermission.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Permission>.Data> c, global::LightSwitchApplication.RolePermission.DetailsClass d, object sf)
                {
                    c(d, ref d._Permission, sf);
                }
                private static bool _Permission_ComputeIsReadOnly(global::LightSwitchApplication.RolePermission e)
                {
                    bool result = false;
                    e.Permission_IsReadOnly(ref result);
                    return result;
                }
                private static void _Permission_Validate(global::LightSwitchApplication.RolePermission e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Permission_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Permission_GetCoreImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d)
                {
                    return d.ImplementationEntity.Permission;
                }
                private static global::LightSwitchApplication.Permission _Permission_GetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass>(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Permission, ref d._Permission);
                }
                private static void _Permission_SetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass d, global::LightSwitchApplication.Permission v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Permission, ref d._Permission, (i, ev) => i.Permission = ev, v);
                }
                private static void _Permission_Refresh(global::LightSwitchApplication.RolePermission.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.RolePermission.DetailsClass.PropertySetProperties.Permission, ref d._Permission);
                }
                private static void _Permission_OnValueChanged(global::LightSwitchApplication.RolePermission e)
                {
                    e.Permission_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>.Data _RoleName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, string>.Data _PermissionId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Role>.Data _Role;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass, global::LightSwitchApplication.Permission>.Data _Permission;
            
        }
    
        #endregion
    }
    
    #endregion
}
