

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class UserRegistration : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the UserRegistration entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UserRegistration()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UserRegistration(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserRegistration> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.UserRegistration.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistration_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserRegistration_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UserName
        {
            get
            {
                return global::LightSwitchApplication.UserRegistration.DetailsClass.GetValue(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.UserName);
            }
            set
            {
                global::LightSwitchApplication.UserRegistration.DetailsClass.SetValue(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.UserName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FullName
        {
            get
            {
                return global::LightSwitchApplication.UserRegistration.DetailsClass.GetValue(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.FullName);
            }
            set
            {
                global::LightSwitchApplication.UserRegistration.DetailsClass.SetValue(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.FullName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Password
        {
            get
            {
                return global::LightSwitchApplication.UserRegistration.DetailsClass.GetValue(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.Password);
            }
            set
            {
                global::LightSwitchApplication.UserRegistration.DetailsClass.SetValue(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.Password, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RoleAssignment> RoleAssignments
        {
            get
            {
                return global::LightSwitchApplication.UserRegistration.DetailsClass.GetValue(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.RoleAssignments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RoleAssignment> RoleAssignmentsQuery
        {
            get
            {
                return global::LightSwitchApplication.UserRegistration.DetailsClass.GetQuery(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.RoleAssignments);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RoleAssignment> DerivingRoleAssignments
        {
            get
            {
                return global::LightSwitchApplication.UserRegistration.DetailsClass.GetValue(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.DerivingRoleAssignments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RoleAssignment> DerivingRoleAssignmentsQuery
        {
            get
            {
                return global::LightSwitchApplication.UserRegistration.DetailsClass.GetQuery(this, global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.DerivingRoleAssignments);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.UserRegistration,
                global::LightSwitchApplication.UserRegistration.DetailsClass,
                global::LightSwitchApplication.UserRegistration.DetailsClass.IImplementation,
                global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.UserName;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass>.Entry
                __UserRegistrationEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass>.Entry(
                    global::LightSwitchApplication.UserRegistration.DetailsClass.__UserRegistration_CreateNew,
                    global::LightSwitchApplication.UserRegistration.DetailsClass.__UserRegistration_Created,
                    global::LightSwitchApplication.UserRegistration.DetailsClass.__UserRegistration_AllowSaveWithErrors);
            private static global::LightSwitchApplication.UserRegistration __UserRegistration_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserRegistration> es)
            {
                return new global::LightSwitchApplication.UserRegistration(es);
            }
            private static void __UserRegistration_Created(global::LightSwitchApplication.UserRegistration e)
            {
                e.UserRegistration_Created();
            }
            private static bool __UserRegistration_AllowSaveWithErrors(global::LightSwitchApplication.UserRegistration e)
            {
                bool result = false;
                e.UserRegistration_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string> UserName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.UserName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string> FullName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.FullName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string> Password
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.Password) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment> RoleAssignments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.RoleAssignments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment> DerivingRoleAssignments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.DerivingRoleAssignments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string UserName { get; set; }
                new string FullName { get; set; }
                new string Password { get; set; }
                new global::System.Collections.IEnumerable RoleAssignments { get; }
                new global::System.Collections.IEnumerable DerivingRoleAssignments { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Entry
                    UserName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Entry(
                        "UserName",
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._UserName_Stub,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._UserName_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._UserName_Validate,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._UserName_GetImplementationValue,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._UserName_SetImplementationValue,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._UserName_OnValueChanged);
                private static void _UserName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserRegistration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserRegistration.DetailsClass d, object sf)
                {
                    c(d, ref d._UserName, sf);
                }
                private static bool _UserName_ComputeIsReadOnly(global::LightSwitchApplication.UserRegistration e)
                {
                    bool result = false;
                    e.UserName_IsReadOnly(ref result);
                    return result;
                }
                private static void _UserName_Validate(global::LightSwitchApplication.UserRegistration e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UserName_Validate(r);
                }
                private static string _UserName_GetImplementationValue(global::LightSwitchApplication.UserRegistration.DetailsClass d)
                {
                    return d.ImplementationEntity.UserName;
                }
                private static void _UserName_SetImplementationValue(global::LightSwitchApplication.UserRegistration.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UserName = v;
                }
                private static void _UserName_OnValueChanged(global::LightSwitchApplication.UserRegistration e)
                {
                    e.UserName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Entry
                    FullName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Entry(
                        "FullName",
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._FullName_Stub,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._FullName_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._FullName_Validate,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._FullName_GetImplementationValue,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._FullName_SetImplementationValue,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._FullName_OnValueChanged);
                private static void _FullName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserRegistration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserRegistration.DetailsClass d, object sf)
                {
                    c(d, ref d._FullName, sf);
                }
                private static bool _FullName_ComputeIsReadOnly(global::LightSwitchApplication.UserRegistration e)
                {
                    bool result = false;
                    e.FullName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FullName_Validate(global::LightSwitchApplication.UserRegistration e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FullName_Validate(r);
                }
                private static string _FullName_GetImplementationValue(global::LightSwitchApplication.UserRegistration.DetailsClass d)
                {
                    return d.ImplementationEntity.FullName;
                }
                private static void _FullName_SetImplementationValue(global::LightSwitchApplication.UserRegistration.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FullName = v;
                }
                private static void _FullName_OnValueChanged(global::LightSwitchApplication.UserRegistration e)
                {
                    e.FullName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Entry
                    Password = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Entry(
                        "Password",
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._Password_Stub,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._Password_ComputeIsReadOnly,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._Password_Validate,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._Password_GetImplementationValue,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._Password_SetImplementationValue,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._Password_OnValueChanged);
                private static void _Password_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserRegistration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Data> c, global::LightSwitchApplication.UserRegistration.DetailsClass d, object sf)
                {
                    c(d, ref d._Password, sf);
                }
                private static bool _Password_ComputeIsReadOnly(global::LightSwitchApplication.UserRegistration e)
                {
                    bool result = false;
                    e.Password_IsReadOnly(ref result);
                    return result;
                }
                private static void _Password_Validate(global::LightSwitchApplication.UserRegistration e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Password_Validate(r);
                }
                private static string _Password_GetImplementationValue(global::LightSwitchApplication.UserRegistration.DetailsClass d)
                {
                    return d.ImplementationEntity.Password;
                }
                private static void _Password_SetImplementationValue(global::LightSwitchApplication.UserRegistration.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Password = v;
                }
                private static void _Password_OnValueChanged(global::LightSwitchApplication.UserRegistration e)
                {
                    e.Password_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>.Entry
                    RoleAssignments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>.Entry(
                        "RoleAssignments",
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._RoleAssignments_Stub,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._RoleAssignments_GetReferencedEntities,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._RoleAssignments_GetEntityCollection);
                private static void _RoleAssignments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserRegistration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>.Data> c, global::LightSwitchApplication.UserRegistration.DetailsClass d, object sf)
                {
                    c(d, ref d._RoleAssignments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RoleAssignment> _RoleAssignments_GetReferencedEntities(global::LightSwitchApplication.UserRegistration.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RoleAssignment, global::LightSwitchApplication.RoleAssignment.DetailsClass>(global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.RoleAssignments, ref d._RoleAssignments);
                }
                private static global::System.Collections.IEnumerable _RoleAssignments_GetEntityCollection(global::LightSwitchApplication.UserRegistration.DetailsClass d)
                {
                    return d.ImplementationEntity.RoleAssignments;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>.Entry
                    DerivingRoleAssignments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>.Entry(
                        "DerivingRoleAssignments",
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._DerivingRoleAssignments_Stub,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._DerivingRoleAssignments_GetReferencedEntities,
                        global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties._DerivingRoleAssignments_GetEntityCollection);
                private static void _DerivingRoleAssignments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UserRegistration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>.Data> c, global::LightSwitchApplication.UserRegistration.DetailsClass d, object sf)
                {
                    c(d, ref d._DerivingRoleAssignments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RoleAssignment> _DerivingRoleAssignments_GetReferencedEntities(global::LightSwitchApplication.UserRegistration.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RoleAssignment, global::LightSwitchApplication.RoleAssignment.DetailsClass>(global::LightSwitchApplication.UserRegistration.DetailsClass.PropertySetProperties.DerivingRoleAssignments, ref d._DerivingRoleAssignments);
                }
                private static global::System.Collections.IEnumerable _DerivingRoleAssignments_GetEntityCollection(global::LightSwitchApplication.UserRegistration.DetailsClass d)
                {
                    return d.ImplementationEntity.DerivingRoleAssignments;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Data _UserName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Data _FullName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, string>.Data _Password;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>.Data _RoleAssignments;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UserRegistration, global::LightSwitchApplication.UserRegistration.DetailsClass, global::LightSwitchApplication.RoleAssignment>.Data _DerivingRoleAssignments;
            
        }
    
        #endregion
    }
    
    #endregion
}
