

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Permission : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Permission entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Permission()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Permission(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Permission> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Permission.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permission_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Permission_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Id
        {
            get
            {
                return global::LightSwitchApplication.Permission.DetailsClass.GetValue(this, global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Permission.DetailsClass.SetValue(this, global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Permission.DetailsClass.GetValue(this, global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Permission.DetailsClass.SetValue(this, global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RolePermission> RolePermissions
        {
            get
            {
                return global::LightSwitchApplication.Permission.DetailsClass.GetValue(this, global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.RolePermissions);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RolePermission> RolePermissionsQuery
        {
            get
            {
                return global::LightSwitchApplication.Permission.DetailsClass.GetQuery(this, global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.RolePermissions);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.MenuTile> MenuTiles
        {
            get
            {
                return global::LightSwitchApplication.Permission.DetailsClass.GetValue(this, global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.MenuTiles);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.MenuTile> MenuTilesQuery
        {
            get
            {
                return global::LightSwitchApplication.Permission.DetailsClass.GetQuery(this, global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.MenuTiles);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Permission,
                global::LightSwitchApplication.Permission.DetailsClass,
                global::LightSwitchApplication.Permission.DetailsClass.IImplementation,
                global::LightSwitchApplication.Permission.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass>.Entry
                __PermissionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass>.Entry(
                    global::LightSwitchApplication.Permission.DetailsClass.__Permission_CreateNew,
                    global::LightSwitchApplication.Permission.DetailsClass.__Permission_Created,
                    global::LightSwitchApplication.Permission.DetailsClass.__Permission_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Permission __Permission_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Permission> es)
            {
                return new global::LightSwitchApplication.Permission(es);
            }
            private static void __Permission_Created(global::LightSwitchApplication.Permission e)
            {
                e.Permission_Created();
            }
            private static bool __Permission_AllowSaveWithErrors(global::LightSwitchApplication.Permission e)
            {
                bool result = false;
                e.Permission_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Permission.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.RolePermission> RolePermissions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.RolePermissions) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.RolePermission>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.MenuTile> MenuTiles
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.MenuTiles) as global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.MenuTile>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string Id { get; set; }
                new string Name { get; set; }
                new global::System.Collections.IEnumerable RolePermissions { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>.Entry(
                        "Id",
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Permission.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>.Data> c, global::LightSwitchApplication.Permission.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Permission e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Permission e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static string _Id_GetImplementationValue(global::LightSwitchApplication.Permission.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Permission.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Permission e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Permission.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>.Data> c, global::LightSwitchApplication.Permission.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Permission e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Permission e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Permission.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Permission.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Permission e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.RolePermission>.Entry
                    RolePermissions = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.RolePermission>.Entry(
                        "RolePermissions",
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._RolePermissions_Stub,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._RolePermissions_GetReferencedEntities,
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._RolePermissions_GetEntityCollection);
                private static void _RolePermissions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Permission.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.RolePermission>.Data> c, global::LightSwitchApplication.Permission.DetailsClass d, object sf)
                {
                    c(d, ref d._RolePermissions, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RolePermission> _RolePermissions_GetReferencedEntities(global::LightSwitchApplication.Permission.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RolePermission, global::LightSwitchApplication.RolePermission.DetailsClass>(global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties.RolePermissions, ref d._RolePermissions);
                }
                private static global::System.Collections.IEnumerable _RolePermissions_GetEntityCollection(global::LightSwitchApplication.Permission.DetailsClass d)
                {
                    return d.ImplementationEntity.RolePermissions;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.MenuTile>.Entry
                    MenuTiles = new global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.MenuTile>.Entry(
                        "MenuTiles",
                        global::LightSwitchApplication.Permission.DetailsClass.PropertySetProperties._MenuTiles_Stub);
                private static void _MenuTiles_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Permission.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.MenuTile>.Data> c, global::LightSwitchApplication.Permission.DetailsClass d, object sf)
                {
                    c(d, ref d._MenuTiles, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.RolePermission>.Data _RolePermissions;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Permission, global::LightSwitchApplication.Permission.DetailsClass, global::LightSwitchApplication.MenuTile>.Data _MenuTiles;
            
        }
    
        #endregion
    }
    
    #endregion
}
