//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/26/2013 6:02:03 PM
namespace LsSecurityData.LsSecurityDataService
{
    
    /// <summary>
    /// There are no comments for SecurityData in the schema.
    /// </summary>
    public partial class SecurityData : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SecurityData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SecurityData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Microsoft.LightSwitch.Security", "LsSecurityData.LsSecurityDataService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LsSecurityData.LsSecurityDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Microsoft.LightSwitch.Security.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for UserRegistrations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UserRegistration> UserRegistrations
        {
            get
            {
                if ((this._UserRegistrations == null))
                {
                    this._UserRegistrations = base.CreateQuery<UserRegistration>("UserRegistrations");
                }
                return this._UserRegistrations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UserRegistration> _UserRegistrations;
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Role> Roles
        {
            get
            {
                if ((this._Roles == null))
                {
                    this._Roles = base.CreateQuery<Role>("Roles");
                }
                return this._Roles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Role> _Roles;
        /// <summary>
        /// There are no comments for RoleAssignments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RoleAssignment> RoleAssignments
        {
            get
            {
                if ((this._RoleAssignments == null))
                {
                    this._RoleAssignments = base.CreateQuery<RoleAssignment>("RoleAssignments");
                }
                return this._RoleAssignments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RoleAssignment> _RoleAssignments;
        /// <summary>
        /// There are no comments for Permissions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Permission> Permissions
        {
            get
            {
                if ((this._Permissions == null))
                {
                    this._Permissions = base.CreateQuery<Permission>("Permissions");
                }
                return this._Permissions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Permission> _Permissions;
        /// <summary>
        /// There are no comments for RolePermissions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RolePermission> RolePermissions
        {
            get
            {
                if ((this._RolePermissions == null))
                {
                    this._RolePermissions = base.CreateQuery<RolePermission>("RolePermissions");
                }
                return this._RolePermissions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RolePermission> _RolePermissions;
        /// <summary>
        /// There are no comments for UserRegistrations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUserRegistrations(UserRegistration userRegistration)
        {
            base.AddObject("UserRegistrations", userRegistration);
        }
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
        /// <summary>
        /// There are no comments for RoleAssignments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRoleAssignments(RoleAssignment roleAssignment)
        {
            base.AddObject("RoleAssignments", roleAssignment);
        }
        /// <summary>
        /// There are no comments for Permissions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPermissions(Permission permission)
        {
            base.AddObject("Permissions", permission);
        }
        /// <summary>
        /// There are no comments for RolePermissions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRolePermissions(RolePermission rolePermission)
        {
            base.AddObject("RolePermissions", rolePermission);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "Namespace=\"Microsoft.LightSwitch.Security\" Alias=\"Self\" xmlns=\"http://schemas.mi" +
                "crosoft.com/ado/2008/09/edm\"><EntityType Name=\"UserRegistration\"><Key><PropertyR" +
                "ef Name=\"UserName\" /></Key><Property Name=\"UserName\" Type=\"Edm.String\" Nullable=" +
                "\"false\" MaxLength=\"256\" /><Property Name=\"FullName\" Type=\"Edm.String\" Nullable=\"" +
                "false\" MaxLength=\"256\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Password\" Type=" +
                "\"Edm.String\" MaxLength=\"128\" ConcurrencyMode=\"Fixed\" /><NavigationProperty Name=" +
                "\"RoleAssignments\" Relationship=\"Microsoft.LightSwitch.Security.RoleAssignment_Us" +
                "er\" ToRole=\"RoleAssignments\" FromRole=\"User\" /><NavigationProperty Name=\"Derivin" +
                "gRoleAssignments\" Relationship=\"Microsoft.LightSwitch.Security.RoleAssignment_So" +
                "urceAccount\" ToRole=\"DerivingRoleAssignments\" FromRole=\"SourceAccount\" /></Entit" +
                "yType><EntityType Name=\"Role\"><Key><PropertyRef Name=\"Name\" /></Key><Property Na" +
                "me=\"Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"128\" /><NavigationProper" +
                "ty Name=\"RoleAssignments\" Relationship=\"Microsoft.LightSwitch.Security.RoleAssig" +
                "nment_Role\" ToRole=\"RoleAssignments\" FromRole=\"Role\" /><NavigationProperty Name=" +
                "\"RolePermissions\" Relationship=\"Microsoft.LightSwitch.Security.RolePermission_Ro" +
                "le\" ToRole=\"RolePermissions\" FromRole=\"Role\" /></EntityType><EntityType Name=\"Ro" +
                "leAssignment\"><Key><PropertyRef Name=\"UserName\" /><PropertyRef Name=\"RoleName\" /" +
                "><PropertyRef Name=\"SourceAccountName\" /></Key><Property Name=\"UserName\" Type=\"E" +
                "dm.String\" Nullable=\"false\" MaxLength=\"256\" /><Property Name=\"RoleName\" Type=\"Ed" +
                "m.String\" Nullable=\"false\" MaxLength=\"128\" /><Property Name=\"SourceAccountName\" " +
                "Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"256\" /><NavigationProperty Name=\"U" +
                "ser\" Relationship=\"Microsoft.LightSwitch.Security.RoleAssignment_User\" ToRole=\"U" +
                "ser\" FromRole=\"RoleAssignments\" /><NavigationProperty Name=\"SourceAccount\" Relat" +
                "ionship=\"Microsoft.LightSwitch.Security.RoleAssignment_SourceAccount\" ToRole=\"So" +
                "urceAccount\" FromRole=\"DerivingRoleAssignments\" /><NavigationProperty Name=\"Role" +
                "\" Relationship=\"Microsoft.LightSwitch.Security.RoleAssignment_Role\" ToRole=\"Role" +
                "\" FromRole=\"RoleAssignments\" /></EntityType><EntityType Name=\"Permission\"><Key><" +
                "PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.String\" Nullable=\"fa" +
                "lse\" MaxLength=\"322\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" " +
                "MaxLength=\"64\" ConcurrencyMode=\"Fixed\" /><NavigationProperty Name=\"RolePermissio" +
                "ns\" Relationship=\"Microsoft.LightSwitch.Security.RolePermission_Permission\" ToRo" +
                "le=\"RolePermissions\" FromRole=\"Permission\" /></EntityType><EntityType Name=\"Role" +
                "Permission\"><Key><PropertyRef Name=\"RoleName\" /><PropertyRef Name=\"PermissionId\"" +
                " /></Key><Property Name=\"RoleName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=" +
                "\"128\" /><Property Name=\"PermissionId\" Type=\"Edm.String\" Nullable=\"false\" MaxLeng" +
                "th=\"322\" /><NavigationProperty Name=\"Role\" Relationship=\"Microsoft.LightSwitch.S" +
                "ecurity.RolePermission_Role\" ToRole=\"Role\" FromRole=\"RolePermissions\" /><Navigat" +
                "ionProperty Name=\"Permission\" Relationship=\"Microsoft.LightSwitch.Security.RoleP" +
                "ermission_Permission\" ToRole=\"Permission\" FromRole=\"RolePermissions\" /></EntityT" +
                "ype><Association Name=\"RoleAssignment_User\"><End Role=\"User\" Type=\"Microsoft.Lig" +
                "htSwitch.Security.UserRegistration\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" " +
                "/></End><End Role=\"RoleAssignments\" Type=\"Microsoft.LightSwitch.Security.RoleAss" +
                "ignment\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"User\"><Prope" +
                "rtyRef Name=\"UserName\" /></Principal><Dependent Role=\"RoleAssignments\"><Property" +
                "Ref Name=\"UserName\" /></Dependent></ReferentialConstraint></Association><Associa" +
                "tion Name=\"RoleAssignment_SourceAccount\"><End Role=\"SourceAccount\" Type=\"Microso" +
                "ft.LightSwitch.Security.UserRegistration\" Multiplicity=\"1\"><OnDelete Action=\"Cas" +
                "cade\" /></End><End Role=\"DerivingRoleAssignments\" Type=\"Microsoft.LightSwitch.Se" +
                "curity.RoleAssignment\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role" +
                "=\"SourceAccount\"><PropertyRef Name=\"UserName\" /></Principal><Dependent Role=\"Der" +
                "ivingRoleAssignments\"><PropertyRef Name=\"SourceAccountName\" /></Dependent></Refe" +
                "rentialConstraint></Association><Association Name=\"RoleAssignment_Role\"><End Rol" +
                "e=\"Role\" Type=\"Microsoft.LightSwitch.Security.Role\" Multiplicity=\"1\" /><End Role" +
                "=\"RoleAssignments\" Type=\"Microsoft.LightSwitch.Security.RoleAssignment\" Multipli" +
                "city=\"*\" /><ReferentialConstraint><Principal Role=\"Role\"><PropertyRef Name=\"Name" +
                "\" /></Principal><Dependent Role=\"RoleAssignments\"><PropertyRef Name=\"RoleName\" /" +
                "></Dependent></ReferentialConstraint></Association><Association Name=\"RolePermis" +
                "sion_Role\"><End Role=\"Role\" Type=\"Microsoft.LightSwitch.Security.Role\" Multiplic" +
                "ity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Role=\"RolePermissions\" Type=\"Mic" +
                "rosoft.LightSwitch.Security.RolePermission\" Multiplicity=\"*\" /><ReferentialConst" +
                "raint><Principal Role=\"Role\"><PropertyRef Name=\"Name\" /></Principal><Dependent R" +
                "ole=\"RolePermissions\"><PropertyRef Name=\"RoleName\" /></Dependent></ReferentialCo" +
                "nstraint></Association><Association Name=\"RolePermission_Permission\"><End Role=\"" +
                "Permission\" Type=\"Microsoft.LightSwitch.Security.Permission\" Multiplicity=\"1\"><O" +
                "nDelete Action=\"Cascade\" /></End><End Role=\"RolePermissions\" Type=\"Microsoft.Lig" +
                "htSwitch.Security.RolePermission\" Multiplicity=\"*\" /><ReferentialConstraint><Pri" +
                "ncipal Role=\"Permission\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"R" +
                "olePermissions\"><PropertyRef Name=\"PermissionId\" /></Dependent></ReferentialCons" +
                "traint></Association><EntityContainer Name=\"SecurityData\" m:IsDefaultEntityConta" +
                "iner=\"true\"><EntitySet Name=\"UserRegistrations\" EntityType=\"Microsoft.LightSwitc" +
                "h.Security.UserRegistration\" /><EntitySet Name=\"Roles\" EntityType=\"Microsoft.Lig" +
                "htSwitch.Security.Role\" /><EntitySet Name=\"RoleAssignments\" EntityType=\"Microsof" +
                "t.LightSwitch.Security.RoleAssignment\" /><EntitySet Name=\"Permissions\" EntityTyp" +
                "e=\"Microsoft.LightSwitch.Security.Permission\" /><EntitySet Name=\"RolePermissions" +
                "\" EntityType=\"Microsoft.LightSwitch.Security.RolePermission\" /><AssociationSet N" +
                "ame=\"RoleAssignment_User\" Association=\"Microsoft.LightSwitch.Security.RoleAssign" +
                "ment_User\"><End Role=\"User\" EntitySet=\"UserRegistrations\" /><End Role=\"RoleAssig" +
                "nments\" EntitySet=\"RoleAssignments\" /></AssociationSet><AssociationSet Name=\"Rol" +
                "eAssignment_SourceAccount\" Association=\"Microsoft.LightSwitch.Security.RoleAssig" +
                "nment_SourceAccount\"><End Role=\"SourceAccount\" EntitySet=\"UserRegistrations\" /><" +
                "End Role=\"DerivingRoleAssignments\" EntitySet=\"RoleAssignments\" /></AssociationSe" +
                "t><AssociationSet Name=\"RoleAssignment_Role\" Association=\"Microsoft.LightSwitch." +
                "Security.RoleAssignment_Role\"><End Role=\"Role\" EntitySet=\"Roles\" /><End Role=\"Ro" +
                "leAssignments\" EntitySet=\"RoleAssignments\" /></AssociationSet><AssociationSet Na" +
                "me=\"RolePermission_Role\" Association=\"Microsoft.LightSwitch.Security.RolePermiss" +
                "ion_Role\"><End Role=\"Role\" EntitySet=\"Roles\" /><End Role=\"RolePermissions\" Entit" +
                "ySet=\"RolePermissions\" /></AssociationSet><AssociationSet Name=\"RolePermission_P" +
                "ermission\" Association=\"Microsoft.LightSwitch.Security.RolePermission_Permission" +
                "\"><End Role=\"Permission\" EntitySet=\"Permissions\" /><End Role=\"RolePermissions\" E" +
                "ntitySet=\"RolePermissions\" /></AssociationSet><FunctionImport Name=\"Microsoft_Li" +
                "ghtSwitch_GetCanInformation\" ReturnType=\"Edm.String\" m:Http";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @"Method=""GET""><Parameter Name=""dataServiceMembers"" Type=""Edm.String"" Mode=""In"" /></FunctionImport><FunctionImport Name=""ChangePassword"" m:HttpMethod=""POST""><Parameter Name=""userName"" Type=""Edm.String"" Mode=""In"" /><Parameter Name=""oldPassword"" Type=""Edm.String"" Mode=""In"" /><Parameter Name=""newPassword"" Type=""Edm.String"" Mode=""In"" /></FunctionImport><FunctionImport Name=""IsValidPassword"" ReturnType=""Edm.Boolean"" m:HttpMethod=""POST""><Parameter Name=""password"" Type=""Edm.String"" Mode=""In"" /></FunctionImport><FunctionImport Name=""GetWindowsUserInfo"" ReturnType=""Edm.String"" m:HttpMethod=""GET""><Parameter Name=""userName"" Type=""Edm.String"" Mode=""In"" /></FunctionImport><FunctionImport Name=""GetAuthenticationType"" ReturnType=""Edm.String"" m:HttpMethod=""GET"" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Microsoft.LightSwitch.Security.UserRegistration in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("UserName")]
    public partial class UserRegistration
    {
        /// <summary>
        /// Create a new UserRegistration object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="fullName">Initial value of FullName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserRegistration CreateUserRegistration(string userName, string fullName)
        {
            UserRegistration userRegistration = new UserRegistration();
            userRegistration.UserName = userName;
            userRegistration.FullName = fullName;
            return userRegistration;
        }
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property FullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FullName
        {
            get
            {
                return this._FullName;
            }
            set
            {
                this.OnFullNameChanging(value);
                this._FullName = value;
                this.OnFullNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FullName;
        partial void OnFullNameChanging(string value);
        partial void OnFullNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for RoleAssignments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<RoleAssignment> RoleAssignments
        {
            get
            {
                return this._RoleAssignments;
            }
            set
            {
                if ((value != null))
                {
                    this._RoleAssignments = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<RoleAssignment> _RoleAssignments = new global::System.Collections.ObjectModel.Collection<RoleAssignment>();
        /// <summary>
        /// There are no comments for DerivingRoleAssignments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<RoleAssignment> DerivingRoleAssignments
        {
            get
            {
                return this._DerivingRoleAssignments;
            }
            set
            {
                if ((value != null))
                {
                    this._DerivingRoleAssignments = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<RoleAssignment> _DerivingRoleAssignments = new global::System.Collections.ObjectModel.Collection<RoleAssignment>();
    }
    /// <summary>
    /// There are no comments for Microsoft.LightSwitch.Security.Role in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
    public partial class Role
    {
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Role CreateRole(string name)
        {
            Role role = new Role();
            role.Name = name;
            return role;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for RoleAssignments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<RoleAssignment> RoleAssignments
        {
            get
            {
                return this._RoleAssignments;
            }
            set
            {
                if ((value != null))
                {
                    this._RoleAssignments = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<RoleAssignment> _RoleAssignments = new global::System.Collections.ObjectModel.Collection<RoleAssignment>();
        /// <summary>
        /// There are no comments for RolePermissions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<RolePermission> RolePermissions
        {
            get
            {
                return this._RolePermissions;
            }
            set
            {
                if ((value != null))
                {
                    this._RolePermissions = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<RolePermission> _RolePermissions = new global::System.Collections.ObjectModel.Collection<RolePermission>();
    }
    /// <summary>
    /// There are no comments for Microsoft.LightSwitch.Security.RoleAssignment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// RoleName
    /// SourceAccountName
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("UserName", "RoleName", "SourceAccountName")]
    public partial class RoleAssignment
    {
        /// <summary>
        /// Create a new RoleAssignment object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="roleName">Initial value of RoleName.</param>
        /// <param name="sourceAccountName">Initial value of SourceAccountName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RoleAssignment CreateRoleAssignment(string userName, string roleName, string sourceAccountName)
        {
            RoleAssignment roleAssignment = new RoleAssignment();
            roleAssignment.UserName = userName;
            roleAssignment.RoleName = roleName;
            roleAssignment.SourceAccountName = sourceAccountName;
            return roleAssignment;
        }
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property RoleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RoleName
        {
            get
            {
                return this._RoleName;
            }
            set
            {
                this.OnRoleNameChanging(value);
                this._RoleName = value;
                this.OnRoleNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RoleName;
        partial void OnRoleNameChanging(string value);
        partial void OnRoleNameChanged();
        /// <summary>
        /// There are no comments for Property SourceAccountName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SourceAccountName
        {
            get
            {
                return this._SourceAccountName;
            }
            set
            {
                this.OnSourceAccountNameChanging(value);
                this._SourceAccountName = value;
                this.OnSourceAccountNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SourceAccountName;
        partial void OnSourceAccountNameChanging(string value);
        partial void OnSourceAccountNameChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public UserRegistration User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private UserRegistration _User;
        /// <summary>
        /// There are no comments for SourceAccount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public UserRegistration SourceAccount
        {
            get
            {
                return this._SourceAccount;
            }
            set
            {
                this._SourceAccount = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private UserRegistration _SourceAccount;
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Role Role
        {
            get
            {
                return this._Role;
            }
            set
            {
                this._Role = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Role _Role;
    }
    /// <summary>
    /// There are no comments for Microsoft.LightSwitch.Security.Permission in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Permission
    {
        /// <summary>
        /// Create a new Permission object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Permission CreatePermission(string ID, string name)
        {
            Permission permission = new Permission();
            permission.Id = ID;
            permission.Name = name;
            return permission;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for RolePermissions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<RolePermission> RolePermissions
        {
            get
            {
                return this._RolePermissions;
            }
            set
            {
                if ((value != null))
                {
                    this._RolePermissions = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<RolePermission> _RolePermissions = new global::System.Collections.ObjectModel.Collection<RolePermission>();
    }
    /// <summary>
    /// There are no comments for Microsoft.LightSwitch.Security.RolePermission in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RoleName
    /// PermissionId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("RoleName", "PermissionId")]
    public partial class RolePermission
    {
        /// <summary>
        /// Create a new RolePermission object.
        /// </summary>
        /// <param name="roleName">Initial value of RoleName.</param>
        /// <param name="permissionId">Initial value of PermissionId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RolePermission CreateRolePermission(string roleName, string permissionId)
        {
            RolePermission rolePermission = new RolePermission();
            rolePermission.RoleName = roleName;
            rolePermission.PermissionId = permissionId;
            return rolePermission;
        }
        /// <summary>
        /// There are no comments for Property RoleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RoleName
        {
            get
            {
                return this._RoleName;
            }
            set
            {
                this.OnRoleNameChanging(value);
                this._RoleName = value;
                this.OnRoleNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RoleName;
        partial void OnRoleNameChanging(string value);
        partial void OnRoleNameChanged();
        /// <summary>
        /// There are no comments for Property PermissionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PermissionId
        {
            get
            {
                return this._PermissionId;
            }
            set
            {
                this.OnPermissionIdChanging(value);
                this._PermissionId = value;
                this.OnPermissionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PermissionId;
        partial void OnPermissionIdChanging(string value);
        partial void OnPermissionIdChanged();
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Role Role
        {
            get
            {
                return this._Role;
            }
            set
            {
                this._Role = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Role _Role;
        /// <summary>
        /// There are no comments for Permission in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Permission Permission
        {
            get
            {
                return this._Permission;
            }
            set
            {
                this._Permission = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Permission _Permission;
    }
}
