/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/


/* ==============================================================*/
/* Comment out the following section before pushing to Azure */
/* As Azure does not support the DBCC and resetting Identity seeds */
/* ==============================================================*/

/* Zero out our tables */
/* ======================================== */
/* ======================================== */
/* Only do this for initial deployment!!!! */
/* Careful as this will destroy on every push */
/* ======================================== */
/* ======================================== */

DELETE FROM Icons
GO
DELETE FROM MenuTiles
GO
DELETE FROM Menus
GO

/* Reset our identity counters */
DBCC CHECKIDENT(MenuTiles,reseed,0)
DBCC CHECKIDENT(Menus,reseed,0)
DBCC CHECKIDENT(Icons,reseed,0)
/* ==============================================================*/
/* End of the incompatible code for Azure */
/* When pushing to Azure... comment out the above */
/* ==============================================================*/

/* Add default menus */
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
INSERT Menus(Name, Screen) VALUES (N'Start', N'Start')
INSERT Menus(Name, Screen) VALUES (N'Admin', N'Admin')
GO

/* Add default tiles */
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
INSERT MenuTiles([Order], TileColor, Type, Name, Size, OnClick, Status, PermissionId, MenuTile_Menu) VALUES (1, N'#1182c5', N'simple', N'Profile', N'default', N'myapp.showScreen(''Profile'')', N'Profile', NULL, 1)
INSERT MenuTiles([Order], TileColor, Type, Name, Size, OnClick, Status, PermissionId, MenuTile_Menu) VALUES (10, N'#06834e', N'simple', N'Icons', N'default', N'myapp.showScreen(''IconsBrowse'')', N'Icons', NULL, 2)
INSERT MenuTiles([Order], TileColor, Type, Name, Size, OnClick, Status, PermissionId, MenuTile_Menu) VALUES (8, N'#90258d', N'simple', N'Menus', N'double', N'myapp.showScreen(''MenusBrowse'')', N'Menu Administration', NULL, 2)
INSERT MenuTiles([Order], TileColor, Type, Name, Size, OnClick, Status, PermissionId, MenuTile_Menu) VALUES (6, N'#6f6c07', N'simple', N'Permissions', N'default', N'myapp.showScreen(''PermissionsBrowse'')', N'Permissions', NULL, 2)
INSERT MenuTiles([Order], TileColor, Type, Name, Size, OnClick, Status, PermissionId, MenuTile_Menu) VALUES (4, N'#9f041e', N'simple', N'Roles', N'default', N'myapp.showScreen(''RolesBrowse'')', N'Roles', NULL, 2)
INSERT MenuTiles([Order], TileColor, Type, Name, Size, OnClick, Status, PermissionId, MenuTile_Menu) VALUES (2, N'#1fb800', N'simple', N'Users', N'double', N'myapp.showScreen(''UserRegistrationsBrowse'')', N'User Registrations', NULL, 2)
INSERT MenuTiles([Order], TileColor, Type, Name, Size, OnClick, Status, PermissionId, MenuTile_Menu) VALUES (2, N'#ff3b00', N'simple', N'Admin', N'double', N'myapp.showScreen(''Admin'')', N'Admin', N'Microsoft.LightSwitch.Security:SecurityAdministration', 1)
GO

/* Add Icons to the Icons table */
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
INSERT Icons(Name) VALUES (N'icon-accessibility')
INSERT Icons(Name) VALUES (N'icon-accessibility-2')
INSERT Icons(Name) VALUES (N'icon-address-book')
INSERT Icons(Name) VALUES (N'icon-air')
INSERT Icons(Name) VALUES (N'icon-alarm')
INSERT Icons(Name) VALUES (N'icon-alarm-2')
INSERT Icons(Name) VALUES (N'icon-alarm-cancel')
INSERT Icons(Name) VALUES (N'icon-alarm-clock')
INSERT Icons(Name) VALUES (N'icon-amazon')
INSERT Icons(Name) VALUES (N'icon-anchor')
INSERT Icons(Name) VALUES (N'icon-android')
INSERT Icons(Name) VALUES (N'icon-apple')
INSERT Icons(Name) VALUES (N'icon-arrow-down')
INSERT Icons(Name) VALUES (N'icon-arrow-down-2')
INSERT Icons(Name) VALUES (N'icon-arrow-down-3')
INSERT Icons(Name) VALUES (N'icon-arrow-down-4')
INSERT Icons(Name) VALUES (N'icon-arrow-down-5')
INSERT Icons(Name) VALUES (N'icon-arrow-down-left')
INSERT Icons(Name) VALUES (N'icon-arrow-down-right')
INSERT Icons(Name) VALUES (N'icon-arrow-left')
INSERT Icons(Name) VALUES (N'icon-arrow-left-2')
INSERT Icons(Name) VALUES (N'icon-arrow-left-3')
INSERT Icons(Name) VALUES (N'icon-arrow-left-4')
INSERT Icons(Name) VALUES (N'icon-arrow-left-5')
INSERT Icons(Name) VALUES (N'icon-arrow-right')
INSERT Icons(Name) VALUES (N'icon-arrow-right-2')
INSERT Icons(Name) VALUES (N'icon-arrow-right-3')
INSERT Icons(Name) VALUES (N'icon-arrow-right-4')
INSERT Icons(Name) VALUES (N'icon-arrow-right-5')
INSERT Icons(Name) VALUES (N'icon-arrow-up')
INSERT Icons(Name) VALUES (N'icon-arrow-up-2')
INSERT Icons(Name) VALUES (N'icon-arrow-up-3')
INSERT Icons(Name) VALUES (N'icon-arrow-up-4')
INSERT Icons(Name) VALUES (N'icon-arrow-up-5')
INSERT Icons(Name) VALUES (N'icon-arrow-up-left')
INSERT Icons(Name) VALUES (N'icon-arrow-up-right')
INSERT Icons(Name) VALUES (N'icon-at')
INSERT Icons(Name) VALUES (N'icon-attachment')
INSERT Icons(Name) VALUES (N'icon-auction')
INSERT Icons(Name) VALUES (N'icon-award-fill')
INSERT Icons(Name) VALUES (N'icon-award-stroke')
INSERT Icons(Name) VALUES (N'icon-backspace')
INSERT Icons(Name) VALUES (N'icon-backspace-2')
INSERT Icons(Name) VALUES (N'icon-barcode')
INSERT Icons(Name) VALUES (N'icon-bars')
INSERT Icons(Name) VALUES (N'icon-basket')
INSERT Icons(Name) VALUES (N'icon-battery')
INSERT Icons(Name) VALUES (N'icon-battery-2')
INSERT Icons(Name) VALUES (N'icon-battery-3')
INSERT Icons(Name) VALUES (N'icon-battery-4')
INSERT Icons(Name) VALUES (N'icon-battery-5')
INSERT Icons(Name) VALUES (N'icon-battery-charging')
INSERT Icons(Name) VALUES (N'icon-battery-empty')
INSERT Icons(Name) VALUES (N'icon-battery-full')
INSERT Icons(Name) VALUES (N'icon-battery-half')
INSERT Icons(Name) VALUES (N'icon-beaker')
INSERT Icons(Name) VALUES (N'icon-beaker-alt')
INSERT Icons(Name) VALUES (N'icon-bell')
INSERT Icons(Name) VALUES (N'icon-blocked')
INSERT Icons(Name) VALUES (N'icon-blogger')
INSERT Icons(Name) VALUES (N'icon-bluetooth')
INSERT Icons(Name) VALUES (N'icon-book')
INSERT Icons(Name) VALUES (N'icon-bookmark')
INSERT Icons(Name) VALUES (N'icon-bookmark-2')
INSERT Icons(Name) VALUES (N'icon-bookmark-3')
INSERT Icons(Name) VALUES (N'icon-bookmark-4')
INSERT Icons(Name) VALUES (N'icon-box')
INSERT Icons(Name) VALUES (N'icon-box-add')
INSERT Icons(Name) VALUES (N'icon-box-remove')
INSERT Icons(Name) VALUES (N'icon-briefcase')
INSERT Icons(Name) VALUES (N'icon-briefcase-2')
INSERT Icons(Name) VALUES (N'icon-broadcast')
INSERT Icons(Name) VALUES (N'icon-bug')
INSERT Icons(Name) VALUES (N'icon-bus')
INSERT Icons(Name) VALUES (N'icon-busy')
INSERT Icons(Name) VALUES (N'icon-cabinet')
INSERT Icons(Name) VALUES (N'icon-calculate')
INSERT Icons(Name) VALUES (N'icon-calendar')
INSERT Icons(Name) VALUES (N'icon-camera')
INSERT Icons(Name) VALUES (N'icon-camera-2')
INSERT Icons(Name) VALUES (N'icon-camera-3')
INSERT Icons(Name) VALUES (N'icon-cancel')
INSERT Icons(Name) VALUES (N'icon-cancel-2')
INSERT Icons(Name) VALUES (N'icon-cars')
INSERT Icons(Name) VALUES (N'icon-cart')
INSERT Icons(Name) VALUES (N'icon-cart-2')
INSERT Icons(Name) VALUES (N'icon-cc')
INSERT Icons(Name) VALUES (N'icon-cc-by')
INSERT Icons(Name) VALUES (N'icon-cc-nc')
INSERT Icons(Name) VALUES (N'icon-cc-nc-eu')
INSERT Icons(Name) VALUES (N'icon-cc-nc-jp')
INSERT Icons(Name) VALUES (N'icon-cc-nd')
INSERT Icons(Name) VALUES (N'icon-cc-pd')
INSERT Icons(Name) VALUES (N'icon-cc-sa')
INSERT Icons(Name) VALUES (N'icon-cc-share')
INSERT Icons(Name) VALUES (N'icon-cc-share-2')
INSERT Icons(Name) VALUES (N'icon-cc-zero')
INSERT Icons(Name) VALUES (N'icon-Celsius')
INSERT Icons(Name) VALUES (N'icon-chart-alt')
INSERT Icons(Name) VALUES (N'icon-checkbox')
INSERT Icons(Name) VALUES (N'icon-checkbox-partial')
INSERT Icons(Name) VALUES (N'icon-checkbox-unchecked')
INSERT Icons(Name) VALUES (N'icon-checkmark')
INSERT Icons(Name) VALUES (N'icon-chrome')
INSERT Icons(Name) VALUES (N'icon-chronometer')
INSERT Icons(Name) VALUES (N'icon-clipboard')
INSERT Icons(Name) VALUES (N'icon-clipboard-2')
INSERT Icons(Name) VALUES (N'icon-clock')
INSERT Icons(Name) VALUES (N'icon-cloud')
INSERT Icons(Name) VALUES (N'icon-cloud-2')
INSERT Icons(Name) VALUES (N'icon-cloud-3')
INSERT Icons(Name) VALUES (N'icon-cloud-4')
INSERT Icons(Name) VALUES (N'icon-cloud-5')
INSERT Icons(Name) VALUES (N'icon-cloud-6')
INSERT Icons(Name) VALUES (N'icon-cloud-7')
INSERT Icons(Name) VALUES (N'icon-cloudy')
INSERT Icons(Name) VALUES (N'icon-cloudy-2')
INSERT Icons(Name) VALUES (N'icon-cloudy-3')
INSERT Icons(Name) VALUES (N'icon-cloudy-4')
INSERT Icons(Name) VALUES (N'icon-clubs')
INSERT Icons(Name) VALUES (N'icon-code')
INSERT Icons(Name) VALUES (N'icon-coffee')
INSERT Icons(Name) VALUES (N'icon-cog')
INSERT Icons(Name) VALUES (N'icon-coins')
INSERT Icons(Name) VALUES (N'icon-comments')
INSERT Icons(Name) VALUES (N'icon-comments-2')
INSERT Icons(Name) VALUES (N'icon-comments-3')
INSERT Icons(Name) VALUES (N'icon-comments-4')
INSERT Icons(Name) VALUES (N'icon-comments-5')
INSERT Icons(Name) VALUES (N'icon-compass')
INSERT Icons(Name) VALUES (N'icon-compass-2')
INSERT Icons(Name) VALUES (N'icon-compass-3')
INSERT Icons(Name) VALUES (N'icon-cone')
INSERT Icons(Name) VALUES (N'icon-console')
INSERT Icons(Name) VALUES (N'icon-copy')
INSERT Icons(Name) VALUES (N'icon-credit-card')
INSERT Icons(Name) VALUES (N'icon-css3')
INSERT Icons(Name) VALUES (N'icon-cube')
INSERT Icons(Name) VALUES (N'icon-cube-2')
INSERT Icons(Name) VALUES (N'icon-cycle')
INSERT Icons(Name) VALUES (N'icon-dashboard')
INSERT Icons(Name) VALUES (N'icon-database')
INSERT Icons(Name) VALUES (N'icon-delicious')
INSERT Icons(Name) VALUES (N'icon-deviantart')
INSERT Icons(Name) VALUES (N'icon-diamond')
INSERT Icons(Name) VALUES (N'icon-diamonds')
INSERT Icons(Name) VALUES (N'icon-diary')
INSERT Icons(Name) VALUES (N'icon-direction')
INSERT Icons(Name) VALUES (N'icon-discout')
INSERT Icons(Name) VALUES (N'icon-dollar')
INSERT Icons(Name) VALUES (N'icon-dollar-2')
INSERT Icons(Name) VALUES (N'icon-download')
INSERT Icons(Name) VALUES (N'icon-download-2')
INSERT Icons(Name) VALUES (N'icon-drawer')
INSERT Icons(Name) VALUES (N'icon-drawer-2')
INSERT Icons(Name) VALUES (N'icon-dribbble')
INSERT Icons(Name) VALUES (N'icon-droplet')
INSERT Icons(Name) VALUES (N'icon-earth')
INSERT Icons(Name) VALUES (N'icon-eject')
INSERT Icons(Name) VALUES (N'icon-embed')
INSERT Icons(Name) VALUES (N'icon-enter')
INSERT Icons(Name) VALUES (N'icon-enter-2')
INSERT Icons(Name) VALUES (N'icon-equalizer')
INSERT Icons(Name) VALUES (N'icon-exit')
INSERT Icons(Name) VALUES (N'icon-eye')
INSERT Icons(Name) VALUES (N'icon-eye-2')
INSERT Icons(Name) VALUES (N'icon-facebook')
INSERT Icons(Name) VALUES (N'icon-Fahrenheit')
INSERT Icons(Name) VALUES (N'icon-feed')
INSERT Icons(Name) VALUES (N'icon-file')
INSERT Icons(Name) VALUES (N'icon-file-2')
INSERT Icons(Name) VALUES (N'icon-file-3')
INSERT Icons(Name) VALUES (N'icon-file-4')
INSERT Icons(Name) VALUES (N'icon-file-css')
INSERT Icons(Name) VALUES (N'icon-file-excel')
INSERT Icons(Name) VALUES (N'icon-file-openoffice')
INSERT Icons(Name) VALUES (N'icon-file-pdf')
INSERT Icons(Name) VALUES (N'icon-file-powerpoint')
INSERT Icons(Name) VALUES (N'icon-files')
INSERT Icons(Name) VALUES (N'icon-file-word')
INSERT Icons(Name) VALUES (N'icon-file-xml')
INSERT Icons(Name) VALUES (N'icon-file-zip')
INSERT Icons(Name) VALUES (N'icon-film')
INSERT Icons(Name) VALUES (N'icon-filter')
INSERT Icons(Name) VALUES (N'icon-finder')
INSERT Icons(Name) VALUES (N'icon-fire')
INSERT Icons(Name) VALUES (N'icon-firefox')
INSERT Icons(Name) VALUES (N'icon-first')
INSERT Icons(Name) VALUES (N'icon-first-2')
INSERT Icons(Name) VALUES (N'icon-flag')
INSERT Icons(Name) VALUES (N'icon-flag-2')
INSERT Icons(Name) VALUES (N'icon-flattr')
INSERT Icons(Name) VALUES (N'icon-flickr')
INSERT Icons(Name) VALUES (N'icon-flip')
INSERT Icons(Name) VALUES (N'icon-flip-2')
INSERT Icons(Name) VALUES (N'icon-floppy')
INSERT Icons(Name) VALUES (N'icon-folder')
INSERT Icons(Name) VALUES (N'icon-folder-2')
INSERT Icons(Name) VALUES (N'icon-font')
INSERT Icons(Name) VALUES (N'icon-forrst')
INSERT Icons(Name) VALUES (N'icon-forward')
INSERT Icons(Name) VALUES (N'icon-foursquare')
INSERT Icons(Name) VALUES (N'icon-fullscreen-alt')
INSERT Icons(Name) VALUES (N'icon-fullscreen-exit-alt')
INSERT Icons(Name) VALUES (N'icon-gift')
INSERT Icons(Name) VALUES (N'icon-git')
INSERT Icons(Name) VALUES (N'icon-github')
INSERT Icons(Name) VALUES (N'icon-github-2')
INSERT Icons(Name) VALUES (N'icon-github-3')
INSERT Icons(Name) VALUES (N'icon-github-4')
INSERT Icons(Name) VALUES (N'icon-github-5')
INSERT Icons(Name) VALUES (N'icon-github-6')
INSERT Icons(Name) VALUES (N'icon-glasses')
INSERT Icons(Name) VALUES (N'icon-glasses-2')
INSERT Icons(Name) VALUES (N'icon-globe')
INSERT Icons(Name) VALUES (N'icon-google')
INSERT Icons(Name) VALUES (N'icon-google-drive')
INSERT Icons(Name) VALUES (N'icon-google-plus')
INSERT Icons(Name) VALUES (N'icon-grid')
INSERT Icons(Name) VALUES (N'icon-grid-view')
INSERT Icons(Name) VALUES (N'icon-hash')
INSERT Icons(Name) VALUES (N'icon-headphones')
INSERT Icons(Name) VALUES (N'icon-heart')
INSERT Icons(Name) VALUES (N'icon-heart-2')
INSERT Icons(Name) VALUES (N'icon-help')
INSERT Icons(Name) VALUES (N'icon-help-2')
INSERT Icons(Name) VALUES (N'icon-history')
INSERT Icons(Name) VALUES (N'icon-home')
INSERT Icons(Name) VALUES (N'icon-html5')
INSERT Icons(Name) VALUES (N'icon-html5-2')
INSERT Icons(Name) VALUES (N'icon-IcoMoon')
INSERT Icons(Name) VALUES (N'icon-IE')
INSERT Icons(Name) VALUES (N'icon-image')
INSERT Icons(Name) VALUES (N'icon-info')
INSERT Icons(Name) VALUES (N'icon-info-2')
INSERT Icons(Name) VALUES (N'icon-instagram')
INSERT Icons(Name) VALUES (N'icon-joomla')
INSERT Icons(Name) VALUES (N'icon-key')
INSERT Icons(Name) VALUES (N'icon-key-2')
INSERT Icons(Name) VALUES (N'icon-keyboard')
INSERT Icons(Name) VALUES (N'icon-lab')
INSERT Icons(Name) VALUES (N'icon-lamp')
INSERT Icons(Name) VALUES (N'icon-lamp-2')
INSERT Icons(Name) VALUES (N'icon-laptop')
INSERT Icons(Name) VALUES (N'icon-last')
INSERT Icons(Name) VALUES (N'icon-last-2')
INSERT Icons(Name) VALUES (N'icon-lastfm')
INSERT Icons(Name) VALUES (N'icon-layers')
INSERT Icons(Name) VALUES (N'icon-layers-alt')
INSERT Icons(Name) VALUES (N'icon-left-quote')
INSERT Icons(Name) VALUES (N'icon-left-quote-alt')
INSERT Icons(Name) VALUES (N'icon-left-to-right')
INSERT Icons(Name) VALUES (N'icon-libreoffice')
INSERT Icons(Name) VALUES (N'icon-lightning')
INSERT Icons(Name) VALUES (N'icon-lightning-2')
INSERT Icons(Name) VALUES (N'icon-lightning-3')
INSERT Icons(Name) VALUES (N'icon-lightning-4')
INSERT Icons(Name) VALUES (N'icon-lightning-5')
INSERT Icons(Name) VALUES (N'icon-lightning-6')
INSERT Icons(Name) VALUES (N'icon-lines')
INSERT Icons(Name) VALUES (N'icon-link')
INSERT Icons(Name) VALUES (N'icon-link-2')
INSERT Icons(Name) VALUES (N'icon-linkedin')
INSERT Icons(Name) VALUES (N'icon-list')
INSERT Icons(Name) VALUES (N'icon-loading')
INSERT Icons(Name) VALUES (N'icon-loading-2')
INSERT Icons(Name) VALUES (N'icon-location')
INSERT Icons(Name) VALUES (N'icon-location-2')
INSERT Icons(Name) VALUES (N'icon-location-3')
INSERT Icons(Name) VALUES (N'icon-locked')
INSERT Icons(Name) VALUES (N'icon-locked-2')
INSERT Icons(Name) VALUES (N'icon-loop')
INSERT Icons(Name) VALUES (N'icon-mail')
INSERT Icons(Name) VALUES (N'icon-mail-2')
INSERT Icons(Name) VALUES (N'icon-medal')
INSERT Icons(Name) VALUES (N'icon-medal-2')
INSERT Icons(Name) VALUES (N'icon-menu')
INSERT Icons(Name) VALUES (N'icon-meter-fast')
INSERT Icons(Name) VALUES (N'icon-meter-medium')
INSERT Icons(Name) VALUES (N'icon-meter-slow')
INSERT Icons(Name) VALUES (N'icon-mic')
INSERT Icons(Name) VALUES (N'icon-minus')
INSERT Icons(Name) VALUES (N'icon-minus-2')
INSERT Icons(Name) VALUES (N'icon-mobile')
INSERT Icons(Name) VALUES (N'icon-mobile-2')
INSERT Icons(Name) VALUES (N'icon-monitor')
INSERT Icons(Name) VALUES (N'icon-monitor-2')
INSERT Icons(Name) VALUES (N'icon-moon')
INSERT Icons(Name) VALUES (N'icon-moon-2')
INSERT Icons(Name) VALUES (N'icon-mouse')
INSERT Icons(Name) VALUES (N'icon-move')
INSERT Icons(Name) VALUES (N'icon-move-horizontal')
INSERT Icons(Name) VALUES (N'icon-move-vertical')
INSERT Icons(Name) VALUES (N'icon-music')
INSERT Icons(Name) VALUES (N'icon-new')
INSERT Icons(Name) VALUES (N'icon-newspaper')
INSERT Icons(Name) VALUES (N'icon-new-tab')
INSERT Icons(Name) VALUES (N'icon-new-tab-2')
INSERT Icons(Name) VALUES (N'icon-next')
INSERT Icons(Name) VALUES (N'icon-none')
INSERT Icons(Name) VALUES (N'icon-open')
INSERT Icons(Name) VALUES (N'icon-opera')
INSERT Icons(Name) VALUES (N'icon-paragraph-center')
INSERT Icons(Name) VALUES (N'icon-paragraph-justify')
INSERT Icons(Name) VALUES (N'icon-paragraph-left')
INSERT Icons(Name) VALUES (N'icon-paragraph-right')
INSERT Icons(Name) VALUES (N'icon-pause')
INSERT Icons(Name) VALUES (N'icon-pause-2')
INSERT Icons(Name) VALUES (N'icon-paypal')
INSERT Icons(Name) VALUES (N'icon-pencil')
INSERT Icons(Name) VALUES (N'icon-phone')
INSERT Icons(Name) VALUES (N'icon-phone-2')
INSERT Icons(Name) VALUES (N'icon-picassa')
INSERT Icons(Name) VALUES (N'icon-pictures')
INSERT Icons(Name) VALUES (N'icon-pie')
INSERT Icons(Name) VALUES (N'icon-pilcrow')
INSERT Icons(Name) VALUES (N'icon-pinterest')
INSERT Icons(Name) VALUES (N'icon-play')
INSERT Icons(Name) VALUES (N'icon-play-2')
INSERT Icons(Name) VALUES (N'icon-play-alt')
INSERT Icons(Name) VALUES (N'icon-playlist')
INSERT Icons(Name) VALUES (N'icon-plus')
INSERT Icons(Name) VALUES (N'icon-plus-2')
INSERT Icons(Name) VALUES (N'icon-pointer')
INSERT Icons(Name) VALUES (N'icon-pop-in')
INSERT Icons(Name) VALUES (N'icon-pop-out')
INSERT Icons(Name) VALUES (N'icon-power')
INSERT Icons(Name) VALUES (N'icon-power-2')
INSERT Icons(Name) VALUES (N'icon-previous')
INSERT Icons(Name) VALUES (N'icon-printer')
INSERT Icons(Name) VALUES (N'icon-puzzle')
INSERT Icons(Name) VALUES (N'icon-radio-checked')
INSERT Icons(Name) VALUES (N'icon-radio-unchecked')
INSERT Icons(Name) VALUES (N'icon-rainbow')
INSERT Icons(Name) VALUES (N'icon-rainy')
INSERT Icons(Name) VALUES (N'icon-rainy-2')
INSERT Icons(Name) VALUES (N'icon-rainy-3')
INSERT Icons(Name) VALUES (N'icon-rainy-4')
INSERT Icons(Name) VALUES (N'icon-record')
INSERT Icons(Name) VALUES (N'icon-reddit')
INSERT Icons(Name) VALUES (N'icon-redo')
INSERT Icons(Name) VALUES (N'icon-remove')
INSERT Icons(Name) VALUES (N'icon-reply')
INSERT Icons(Name) VALUES (N'icon-reply-2')
INSERT Icons(Name) VALUES (N'icon-resize')
INSERT Icons(Name) VALUES (N'icon-right-quote')
INSERT Icons(Name) VALUES (N'icon-right-quote-alt')
INSERT Icons(Name) VALUES (N'icon-right-to-left')
INSERT Icons(Name) VALUES (N'icon-rocket')
INSERT Icons(Name) VALUES (N'icon-ruler')
INSERT Icons(Name) VALUES (N'icon-safari')
INSERT Icons(Name) VALUES (N'icon-sale')
INSERT Icons(Name) VALUES (N'icon-satellite')
INSERT Icons(Name) VALUES (N'icon-scissors')
INSERT Icons(Name) VALUES (N'icon-screen')
INSERT Icons(Name) VALUES (N'icon-search')
INSERT Icons(Name) VALUES (N'icon-share')
INSERT Icons(Name) VALUES (N'icon-share-2')
INSERT Icons(Name) VALUES (N'icon-share-3')
INSERT Icons(Name) VALUES (N'icon-shipping')
INSERT Icons(Name) VALUES (N'icon-shit')
INSERT Icons(Name) VALUES (N'icon-skype')
INSERT Icons(Name) VALUES (N'icon-smiley')
INSERT Icons(Name) VALUES (N'icon-snowflake')
INSERT Icons(Name) VALUES (N'icon-snowy')
INSERT Icons(Name) VALUES (N'icon-snowy-2')
INSERT Icons(Name) VALUES (N'icon-snowy-3')
INSERT Icons(Name) VALUES (N'icon-snowy-4')
INSERT Icons(Name) VALUES (N'icon-snowy-5')
INSERT Icons(Name) VALUES (N'icon-soundcloud')
INSERT Icons(Name) VALUES (N'icon-spades')
INSERT Icons(Name) VALUES (N'icon-spin')
INSERT Icons(Name) VALUES (N'icon-star')
INSERT Icons(Name) VALUES (N'icon-star-2')
INSERT Icons(Name) VALUES (N'icon-star-3')
INSERT Icons(Name) VALUES (N'icon-star-4')
INSERT Icons(Name) VALUES (N'icon-stats')
INSERT Icons(Name) VALUES (N'icon-stats-2')
INSERT Icons(Name) VALUES (N'icon-stats-3')
INSERT Icons(Name) VALUES (N'icon-stats-up')
INSERT Icons(Name) VALUES (N'icon-steering-wheel')
INSERT Icons(Name) VALUES (N'icon-stop')
INSERT Icons(Name) VALUES (N'icon-stop-2')
INSERT Icons(Name) VALUES (N'icon-stop-3')
INSERT Icons(Name) VALUES (N'icon-stumbleupon')
INSERT Icons(Name) VALUES (N'icon-sun')
INSERT Icons(Name) VALUES (N'icon-sun-2')
INSERT Icons(Name) VALUES (N'icon-sun-3')
INSERT Icons(Name) VALUES (N'icon-sunrise')
INSERT Icons(Name) VALUES (N'icon-support')
INSERT Icons(Name) VALUES (N'icon-switch')
INSERT Icons(Name) VALUES (N'icon-tab')
INSERT Icons(Name) VALUES (N'icon-tab-2')
INSERT Icons(Name) VALUES (N'icon-tablet')
INSERT Icons(Name) VALUES (N'icon-tag')
INSERT Icons(Name) VALUES (N'icon-target')
INSERT Icons(Name) VALUES (N'icon-target-2')
INSERT Icons(Name) VALUES (N'icon-thermometer')
INSERT Icons(Name) VALUES (N'icon-thumbs-down')
INSERT Icons(Name) VALUES (N'icon-thumbs-up')
INSERT Icons(Name) VALUES (N'icon-ticket')
INSERT Icons(Name) VALUES (N'icon-tools')
INSERT Icons(Name) VALUES (N'icon-tree-view')
INSERT Icons(Name) VALUES (N'icon-trophy')
INSERT Icons(Name) VALUES (N'icon-tumblr')
INSERT Icons(Name) VALUES (N'icon-tux')
INSERT Icons(Name) VALUES (N'icon-tv')
INSERT Icons(Name) VALUES (N'icon-twitter')
INSERT Icons(Name) VALUES (N'icon-type')
INSERT Icons(Name) VALUES (N'icon-umbrella')
INSERT Icons(Name) VALUES (N'icon-undo')
INSERT Icons(Name) VALUES (N'icon-unlocked')
INSERT Icons(Name) VALUES (N'icon-upload')
INSERT Icons(Name) VALUES (N'icon-upload-2')
INSERT Icons(Name) VALUES (N'icon-upload-3')
INSERT Icons(Name) VALUES (N'icon-user')
INSERT Icons(Name) VALUES (N'icon-user-2')
INSERT Icons(Name) VALUES (N'icon-user-3')
INSERT Icons(Name) VALUES (N'icon-vimeo')
INSERT Icons(Name) VALUES (N'icon-volume')
INSERT Icons(Name) VALUES (N'icon-volume-2')
INSERT Icons(Name) VALUES (N'icon-volume-3')
INSERT Icons(Name) VALUES (N'icon-volume-4')
INSERT Icons(Name) VALUES (N'icon-volume-5')
INSERT Icons(Name) VALUES (N'icon-volume-6')
INSERT Icons(Name) VALUES (N'icon-volume-mute')
INSERT Icons(Name) VALUES (N'icon-warning')
INSERT Icons(Name) VALUES (N'icon-weather')
INSERT Icons(Name) VALUES (N'icon-weather-2')
INSERT Icons(Name) VALUES (N'icon-weather-3')
INSERT Icons(Name) VALUES (N'icon-weather-4')
INSERT Icons(Name) VALUES (N'icon-weather-5')
INSERT Icons(Name) VALUES (N'icon-wind')
INSERT Icons(Name) VALUES (N'icon-window')
INSERT Icons(Name) VALUES (N'icon-windows')
INSERT Icons(Name) VALUES (N'icon-windy')
INSERT Icons(Name) VALUES (N'icon-windy-2')
INSERT Icons(Name) VALUES (N'icon-windy-3')
INSERT Icons(Name) VALUES (N'icon-windy-4')
INSERT Icons(Name) VALUES (N'icon-windy-5')
INSERT Icons(Name) VALUES (N'icon-wordpress')
INSERT Icons(Name) VALUES (N'icon-wrench')
INSERT Icons(Name) VALUES (N'icon-xing')
INSERT Icons(Name) VALUES (N'icon-yahoo')
INSERT Icons(Name) VALUES (N'icon-yelp')
INSERT Icons(Name) VALUES (N'icon-youtube')
INSERT Icons(Name) VALUES (N'icon-zip')
INSERT Icons(Name) VALUES (N'icon-zip-2')
INSERT Icons(Name) VALUES (N'icon-zoom-in')
INSERT Icons(Name) VALUES (N'icon-zoom-out')
GO
