// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"UserCode/MenuTile.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/MenuExport.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Security.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/IconAddEdit.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/IconsBrowse.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/IconsImport.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/MenuTileAddEdit.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/MenuView.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/RoleView.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Start.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/UserRegistrationAddEdit.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/UserRegistrationView.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/UserRoleAssignmentAddEdit.lsml.js\"></script>");
